markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
    - jekyll-sitemap
    
name: Vikas Gorur
url: http://vikasgorur.github.io/
description: Words and things.
twitter: vikasgorur
